---
- name: Add Docker Apt signing key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker
  apt:
    name: "{{ packages }}"
    update_cache: true
  vars:
    packages:
    - docker-ce 
    - docker-ce-cli 
    - containerd.io

- name: install docker pip module
  pip:
    name: docker
